### ISSUE TITLE
Error When Launching

### ISSUE THREAD

**Issue by TooVeryIcey** [CubeEngine/core#58]
```
[19:42:07 ERROR] [Sponge]: Failed to load plugin: LibCube 1.2.1 (from mods/LibCube.jar)
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Error injecting constructor, java.lang.NullPointerException
  at org.cubeengine.libcube.LibCube.<init>(LibCube.java:45)
  at org.spongepowered.common.inject.plugin.PluginModule.configure(PluginModule.java:59)
  while locating org.cubeengine.libcube.LibCube

1 error
        at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470) ~[spongevanilla-1.12.2-7.1.0-BETA-33.jar:1.12.2-7.1.0-BETA-33]
        at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:184) ~[spongevanilla-1.12.2-7.1.0-BETA-33.jar:1.12.2-7.1.0-BETA-33]
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110) ~[spongevanilla-1.12.2-7.1.0-BETA-33.jar:1.12.2-7.1.0-BETA-33]
        at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:232) ~[spongevanilla-1.12.2-7.1.0-BETA-33.jar:1.12.2-7.1.0-BETA-33]
        at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:236) ~[spongevanilla-1.12.2-7.1.0-BETA-33.jar:1.12.2-7.1.0-BETA-33]
        at org.spongepowered.server.plugin.VanillaPluginContainer.<init>(VanillaPluginContainer.java:43) ~[VanillaPluginContainer.class:1.12.2-7.1.0-BETA-33]
        at org.spongepowered.server.plugin.VanillaPluginManager.loadPlugin(VanillaPluginManager.java:165) ~[VanillaPluginManager.class:1.12.2-7.1.0-BETA-33]
        at java.util.ArrayList.forEach(ArrayList.java:1257) [?:1.8.0_162]
        at org.spongepowered.server.plugin.VanillaPluginManager.loadPlugins(VanillaPluginManager.java:88) [VanillaPluginManager.class:1.12.2-7.1.0-BETA-33]
        at org.spongepowered.server.SpongeVanilla.preInitialize(SpongeVanilla.java:118) [SpongeVanilla.class:1.12.2-7.1.0-BETA-33]
        at net.minecraft.server.dedicated.DedicatedServer.handler$onServerLoad$bac000(SourceFile:1234) [nz.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(SourceFile:117) [nz.class:?]
        at net.minecraft.server.MinecraftServer.run(SourceFile:434) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
Caused by: java.lang.NullPointerException
        at org.cubeengine.libcube.service.filesystem.FileUtil.hideFile(FileUtil.java:46) ~[FileUtil.class:?]
        at org.cubeengine.libcube.service.filesystem.FileManager.<init>(FileManager.java:110) ~[FileManager.class:?]
        at org.cubeengine.libcube.ModuleManager.<init>(ModuleManager.java:91) ~[ModuleManager.class:?]
        at org.cubeengine.libcube.LibCube.<init>(LibCube.java:48) ~[LibCube.class:?]
        at org.cubeengine.libcube.LibCube$$FastClassByGuice$$97533299.newInstance(<generated>) ~[LibCube.class:?]
        at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89) ~[spongevanilla-1.12.2-7.1.0-BETA-33.jar:1.12.2-7.1.0-BETA-33]
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:111) ~[spongevanilla-1.12.2-7.1.0-BETA-33.jar:1.12.2-7.1.0-BETA-33]
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90) ~[spongevanilla-1.12.2-7.1.0-BETA-33.jar:1.12.2-7.1.0-BETA-33]
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268) ~[spongevanilla-1.12.2-7.1.0-BETA-33.jar:1.12.2-7.1.0-BETA-33]
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46) ~[spongevanilla-1.12.2-7.1.0-BETA-33.jar:1.12.2-7.1.0-BETA-33]
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092) ~[spongevanilla-1.12.2-7.1.0-BETA-33.jar:1.12.2-7.1.0-BETA-33]
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[spongevanilla-1.12.2-7.1.0-BETA-33.jar:1.12.2-7.1.0-BETA-33]
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194) ~[spongevanilla-1.12.2-7.1.0-BETA-33.jar:1.12.2-7.1.0-BETA-33]
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41) ~[spongevanilla-1.12.2-7.1.0-BETA-33.jar:1.12.2-7.1.0-BETA-33]
        at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:205) ~[spongevanilla-1.12.2-7.1.0-BETA-33.jar:1.12.2-7.1.0-BETA-33]
        at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:199) ~[spongevanilla-1.12.2-7.1.0-BETA-33.jar:1.12.2-7.1.0-BETA-33]
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085) ~[spongevanilla-1.12.2-7.1.0-BETA-33.jar:1.12.2-7.1.0-BETA-33]
        at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:199) ~[spongevanilla-1.12.2-7.1.0-BETA-33.jar:1.12.2-7.1.0-BETA-33]
        at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180) ~[spongevanilla-1.12.2-7.1.0-BETA-33.jar:1.12.2-7.1.0-BETA-33]
        ... 12 more
```

**Comment by Faithcaio** [comment]
This was old code back when modules were not plugins. So I just removed it :)

Checkout the new version on ore:
https://ore.spongepowered.org/CubeEngine/LibCube/versions/1.2.2
